version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: wormap-api-nginx
    ports:
      - "${PORT}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - wormap-network

  php:
    build:
      context: docker/php
    container_name: wormap-api-php
    volumes:
      - ./:/var/www/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    restart: unless-stopped
    networks:
      - wormap-network

networks:
  wormap-network:
    driver: bridge
    name: wormap-network
