version: '3.8'

services:
    nginx:
        image: nginx:alpine
        container_name: wormap-api-nginx
        ports:
            - "${NGINX_PORT}:80"
        env_file:
            - .env
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/app
        depends_on:
            - php
        restart: unless-stopped
        networks:
            - wormap-network

    php:
        build:
            context: docker/php
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        container_name: wormap-api-php
        env_file:
            - .env
        volumes:
            - ./:/var/www/app
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        restart: unless-stopped
        networks:
            - wormap-network

networks:
    wormap-network:
        driver: bridge
        name: wormap-network
